Add ability to select a single space
gergelykalman/confluence-markdown-exporter pull request #21
Opened 2022-07-06 08:52 UTC by Kirisummer

While using the script I needed to export a single space, yet it wasn't possible (or I've missed something).
Patch adds `--space` argument that may be used to match spaces by their keys

2022-08-18 11:57 UTC, gergelykalman commented on confluence-markdown-export.py
> +        print(space)
Please remove this, otherwise it looks good

2022-08-18 11:58 UTC, gergelykalman requested changes
Please remove the print statement, and this is good to go

2022-08-18 12:46 UTC, merged

2022-08-18 12:49 UTC, gergelykalman commented
I ended doing this in a separate branch, thank you! :)

2022-11-15 02:32 UTC, Kirisummer commented
Sorry, I missed the notification :)